# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7d5d37c357016bdf09b3d8e87369f9d6446fc6b58f8d3faa720eed9804517751c891cfbd3ce7811229ee49413716e8c1ab9f4e7ede8c58a59d74251b5927ea6

test:
  secret_key_base: 4d52ef7d71e9b9a440624819507953d1aa46f277efdcd332075bce7dc2bfb8bf5d576fa8ad3b60fbc3b08ac27ca787acdbd7b793b91ecbe60e3b7161bae65008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
